apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-vpa
  namespace: vpa-demo
  labels:
    app: nginx-vpa

spec:
  replicas: 1

  selector:
    matchLabels:
      app: nginx-vpa

  template:
    metadata:
      labels:
        app: nginx-vpa

    spec:
      containers:
      - name: nginx
        image: nginx:1.27

        ports:
        - containerPort: 80

        resources:
          requests:
            cpu: "20m"
            memory: "30Mi"

          limits:
            cpu: "200m"
            memory: "200Mi"
