apiVersion: v1
kind: Pod

metadata:
  name: busybox-dev
  namespace: dev
  labels:
    app: busybox

spec:
  serviceAccountName: developer-sa

  containers:
  - name: busybox
    image: busybox:latest

    command:
      - sleep
      - "3600"
